//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineWeatherSoapService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WeatherResponse", Namespace="http://tempuri.org/")]
    public partial class WeatherResponse : object
    {
        
        private string CityField;
        
        private string DescriptionField;
        
        private System.Nullable<decimal> TemperatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Temperature
        {
            get
            {
                return this.TemperatureField;
            }
            set
            {
                this.TemperatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeCastResponse", Namespace="http://tempuri.org/")]
    public partial class ForeCastResponse : object
    {
        
        private string CityField;
        
        private OnlineWeatherSoapService.WeatherResponse[] DailyForecastsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OnlineWeatherSoapService.WeatherResponse[] DailyForecasts
        {
            get
            {
                return this.DailyForecastsField;
            }
            set
            {
                this.DailyForecastsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OnlineWeatherSoapService.IWeatherSoapService")]
    public interface IWeatherSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherSoapService/GetWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineWeatherSoapService.GetWeatherResponse> GetWeatherAsync(OnlineWeatherSoapService.GetWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeatherSoapService/GetWeeklyForecast", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineWeatherSoapService.GetWeeklyForecastResponse> GetWeeklyForecastAsync(OnlineWeatherSoapService.GetWeeklyForecastRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeather", Namespace="http://tempuri.org/", Order=0)]
        public OnlineWeatherSoapService.GetWeatherRequestBody Body;
        
        public GetWeatherRequest()
        {
        }
        
        public GetWeatherRequest(OnlineWeatherSoapService.GetWeatherRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetWeatherRequestBody()
        {
        }
        
        public GetWeatherRequestBody(string city)
        {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeatherResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineWeatherSoapService.GetWeatherResponseBody Body;
        
        public GetWeatherResponse()
        {
        }
        
        public GetWeatherResponse(OnlineWeatherSoapService.GetWeatherResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeatherResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnlineWeatherSoapService.WeatherResponse GetWeatherResult;
        
        public GetWeatherResponseBody()
        {
        }
        
        public GetWeatherResponseBody(OnlineWeatherSoapService.WeatherResponse GetWeatherResult)
        {
            this.GetWeatherResult = GetWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyForecastRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyForecast", Namespace="http://tempuri.org/", Order=0)]
        public OnlineWeatherSoapService.GetWeeklyForecastRequestBody Body;
        
        public GetWeeklyForecastRequest()
        {
        }
        
        public GetWeeklyForecastRequest(OnlineWeatherSoapService.GetWeeklyForecastRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyForecastRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetWeeklyForecastRequestBody()
        {
        }
        
        public GetWeeklyForecastRequestBody(string city)
        {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyForecastResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyForecastResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineWeatherSoapService.GetWeeklyForecastResponseBody Body;
        
        public GetWeeklyForecastResponse()
        {
        }
        
        public GetWeeklyForecastResponse(OnlineWeatherSoapService.GetWeeklyForecastResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyForecastResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OnlineWeatherSoapService.ForeCastResponse GetWeeklyForecastResult;
        
        public GetWeeklyForecastResponseBody()
        {
        }
        
        public GetWeeklyForecastResponseBody(OnlineWeatherSoapService.ForeCastResponse GetWeeklyForecastResult)
        {
            this.GetWeeklyForecastResult = GetWeeklyForecastResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IWeatherSoapServiceChannel : OnlineWeatherSoapService.IWeatherSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WeatherSoapServiceClient : System.ServiceModel.ClientBase<OnlineWeatherSoapService.IWeatherSoapService>, OnlineWeatherSoapService.IWeatherSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WeatherSoapServiceClient() : 
                base(WeatherSoapServiceClient.GetDefaultBinding(), WeatherSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWeatherSoapService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WeatherSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), WeatherSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WeatherSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WeatherSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WeatherSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineWeatherSoapService.GetWeatherResponse> OnlineWeatherSoapService.IWeatherSoapService.GetWeatherAsync(OnlineWeatherSoapService.GetWeatherRequest request)
        {
            return base.Channel.GetWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineWeatherSoapService.GetWeatherResponse> GetWeatherAsync(string city)
        {
            OnlineWeatherSoapService.GetWeatherRequest inValue = new OnlineWeatherSoapService.GetWeatherRequest();
            inValue.Body = new OnlineWeatherSoapService.GetWeatherRequestBody();
            inValue.Body.city = city;
            return ((OnlineWeatherSoapService.IWeatherSoapService)(this)).GetWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineWeatherSoapService.GetWeeklyForecastResponse> OnlineWeatherSoapService.IWeatherSoapService.GetWeeklyForecastAsync(OnlineWeatherSoapService.GetWeeklyForecastRequest request)
        {
            return base.Channel.GetWeeklyForecastAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineWeatherSoapService.GetWeeklyForecastResponse> GetWeeklyForecastAsync(string city)
        {
            OnlineWeatherSoapService.GetWeeklyForecastRequest inValue = new OnlineWeatherSoapService.GetWeeklyForecastRequest();
            inValue.Body = new OnlineWeatherSoapService.GetWeeklyForecastRequestBody();
            inValue.Body.city = city;
            return ((OnlineWeatherSoapService.IWeatherSoapService)(this)).GetWeeklyForecastAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWeatherSoapService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWeatherSoapService_soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7166/WeatherSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WeatherSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWeatherSoapService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WeatherSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWeatherSoapService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWeatherSoapService_soap,
        }
    }
}
